# Site settings
title: Jorge Luis García
email: jlgarci@clemson.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jorgelgarcia
google_scholar_id: SmFz3DIAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

plugins:
  - jekyll-sitemap