# Site settings
title: Jorge Luis García
email: jlgarcia@tamu.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jorgelgarcia
google_scholar_id: SmFz3DIAAAAJ
orcid_id: 0000-0001-7724-6541

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

url: "https://jorgelgarcia.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap